name: Coin Price dev
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["DEV"]
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
