name: GradePortalWeb2
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["DEV"]
  workflow_dispatch:
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        run: |
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing Docker..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            else
              echo "Docker already installed"
            fi
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: dangnguyen143
          password: dckr_pat_EPIXkQPnfrvzDJNXZbWE0sGkxhE
      - name: Build and push Docker Image
        run: |
          echo "dckr_pat_EPIXkQPnfrvzDJNXZbWE0sGkxhE" | docker login -u dangnguyen143 --password-stdin
          docker build -t dangnguyen143/grade-portal-web-2 .
          docker push dangnguyen143/grade-portal-web-2:1.0.0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"         
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: |
          docker stop grade-portal-web-2 || true 
          docker rm grade-portal-web-2 || true
          docker pull dangnguyen143/grade-portal-web-2:1.0.0
          docker run -d -p 3000:3000 --name grade-portal-web-2 dangnguyen143/grade-portal-web-2:1.0.0
